//
//  OutGoingPresenter.swift
//  appointment
//
//  Created by Youssef Jdidi on 2/24/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol OutGoingPresenterProtocol {
    func set(viewController: OutGoingViewControllerProtocol?)

    func present(outGoingDataSource: [Appointment])
    func presentLoadingView(display: Bool)
}

class OutGoingPresenter: OutGoingPresenterProtocol {

    // MARK: DI
    weak var viewController: OutGoingViewControllerProtocol?

    func set(viewController: OutGoingViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  OutGoingPresenter {

    func present(outGoingDataSource: [Appointment]) {
        viewController?.set(outGoingDataSource: outGoingDataSource)
    }

    func presentLoadingView(display: Bool) {
        viewController?.displayLoadingView(display: display)
    }
}
