//
//  SplashScreenPresenterProtocol.swift
//  appointment
//
//  Created by Raluca Mesterca on 16/04/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol SplashScreenPresenterProtocol {
    func set(viewController: SplashScreenViewControllerProtocol?)
    func present(isUserLoggedIn: Bool)
}

class SplashScreenPresenter: SplashScreenPresenterProtocol {

    // MARK: DI
    weak var viewController: SplashScreenViewControllerProtocol?

    func set(viewController: SplashScreenViewControllerProtocol?) {
        self.viewController = viewController
    }

    func present(isUserLoggedIn: Bool) {
        viewController?.display(isUserLoggedIn: isUserLoggedIn)
    }
}
