//
//  SyncPresenter.swift
//  appointment
//
//  Created by Rachel Polachova on 05/03/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol SyncPresenterProtocol {
    func set(viewController: SyncViewControllerProtocol?)
    func handle(error: SyncError)
    func successSyncing(_ app: SyncApp)
}

class SyncPresenter: SyncPresenterProtocol {

    // MARK: DI
    weak var viewController: SyncViewControllerProtocol?

    func set(viewController: SyncViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  SyncPresenter {

    func handle(error: SyncError) {
        viewController?.display(error: error)
    }
    
    func successSyncing(_ app: SyncApp) {
        viewController?.successSyncing(app)
    }
}
