//
//  InComingInteractorTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 3/3/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky
import Moya

class InComingInteractorTests: XCTestCase {

    // MARK: Mocks
    private let mockPresenter = InComingPresenterProtocolMock()
    private let mockInvitationService = InvitationServiceProtocolMock()
    private let mockUserDataService = CurrentUserDataServiceProtocolMock()
    private let mockErrorHandler = ErrorHandlerProtocolMock()

    private var sut: InComingInteractor!

    // MARK: Test lifecycle
    override func setUp()   {
        super.setUp()
        sut = createInteractor()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
    func testGetInvitationsSuccess() {
        let user = CurrentUserEntity.init(context: TestCoreDataHelper.share.setUpInMemoryManagedObjectContext())
        user.userId = 2
        let appointments = Array.init(repeating: Appointment.mock(), count: 10)
        Perform(mockUserDataService,.fetchCurrentUser(.any, perform: { completion in
            completion(.success(user))
        }))
        Perform(mockInvitationService, .getInvitations(.any, perform: { completion in
            completion(.success(appointments))
        }))
        sut.getInvitations()
        Verify(mockInvitationService, .getInvitations(.any))
        Verify(mockPresenter, .present(incomingDataSource: .value(appointments)))
    }

    func testGetInvitationsFailure() {
        let error: MoyaError = .statusCode(.init(statusCode: 400, data: Data()))
        Perform(mockInvitationService, .getInvitations(.any, perform: { completion in
            completion(.failure(error))
        }))
        sut.getInvitations()
        Verify(mockInvitationService, .getInvitations(.any))
        Verify(mockErrorHandler, .handle(.any))
    }
}

// MARK: Privates
private extension  InComingInteractorTests {

    func createInteractor() ->  InComingInteractor {
        return .init(
            presenter: mockPresenter,
            invitationService: mockInvitationService,
            errorHandler: mockErrorHandler,
            currentUserService: mockUserDataService)
    }
}
