//
//  InComingRouterTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 3/3/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class InComingRouterTests: XCTestCase {

    // MARK: Mocks
    private let mockViewController = InComingViewControllerProtocolMock()
    private let mockStoryboard = StoryboardMock()

    func testGotoInvitationDetail() {
        let sut = createRouter()
        let vc = NewInvitationDetailViewController()
        Given(mockStoryboard, .viewController(identifier: .any, willReturn: vc))
        sut.route(to: .invitationDetail(invitation: Appointment.mock()))
        Verify(mockViewController, .show(.value(vc), sender: .any))
        Verify(mockStoryboard, .viewController(identifier: .matching {
            return $0 as? InvitationDetailStoryboardId == .newInvitationDetail
            }))
    }

    private func createRouter() -> InComingRouter {
        let router = InComingRouter(invitationDetailStoryboard: mockStoryboard)
        router.set(viewController: mockViewController)
        return router
    }
}



