//
//  InComingPresenter.swift
//  appointment
//
//  Created by Youssef Jdidi on 2/24/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol InComingPresenterProtocol {
    func set(viewController: InComingViewControllerProtocol?)
    // add the functions that are called from interactor
    
    func present(incomingDataSource: [Appointment])
    func presentLoadingView(display: Bool)
}

class InComingPresenter: InComingPresenterProtocol {

    // MARK: DI
    weak var viewController: InComingViewControllerProtocol?

    func set(viewController: InComingViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  InComingPresenter {
    
    func present(incomingDataSource: [Appointment]) {
        viewController?.set(incomingDataSource: incomingDataSource)
    }

    func presentLoadingView(display: Bool) {
        viewController?.displayLoadingView(display: display)
    }
}
