//
//  TutorialViewControllerTests.swift
//  appointment
//
//  Created by Raluca Mesterca on 03/03/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky
import SnapshotTesting

class TutorialViewControllerTests: XCTestCase {

    // MARK: Mocks
    private let mockRouter = TutorialRouterProtocolMock()
    private let mockInteractor = TutorialInteractorProtocolMock()

    var sut: TutorialViewController!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()

        record = SnapshotTestsRecordMode.environmentVariableMappingValue
        sut = createViewController()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
    func testNormal() {
        let tutorialSlides = Array(repeating: Tutorial.mock(), count: 10)
        sut.displayTutorialSlides(with: tutorialSlides)
        sut.assertSnapshots()
    }

    func testSkipButtonTapped() {
        sut.skipButtonPressed()
        Verify(mockRouter, .route(to: .value(.home)))
    }

    func testVerticalScrollDisabled() {
        sut.scrollView.contentOffset.y = 30
        sut.scrollViewDidScroll(sut.scrollView)
        XCTAssert(sut.scrollView.contentOffset.y == 0)
    }
}

// MARK: Privates
private extension  TutorialViewControllerTests {

    func createViewController() ->  TutorialViewController {

        let vc = R.storyboard.tutorial.tutorialViewController()!
        vc.view.frame = .init(x: 0, y: 0, width: vc.view.frame.width, height: 1100)
        vc.set(router: mockRouter)
        vc.set(interactor: mockInteractor)
        vc.lifecycle()
        return vc
    }

}
