//
//  TutorialRouterTests.swift
//  appointment
//
//  Created by Raluca Mesterca on 03/03/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class TutorialRouterTests: XCTestCase {

    // MARK: Mocks
    private let mockViewContoller = TutorialViewControllerProtocolMock()
    private let mockRootNavigator = RootNavigatorProtocolMock()
    private let mockStoryboard = StoryboardMock()

    var sut: TutorialRouter!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()

        sut = createRouter()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
//    func testRouteToHome() {
//        let vc = HomeViewController()
//        let navVc = ApplicationNavigationController(rootViewController: vc)
//        Given(mockStoryboard, .viewController(identifier: .any, willReturn: vc))
//
//        sut.route(to: .home)
//
//        Verify(mockStoryboard, .viewController(identifier: .matching({ return $0 as? HomeStoryboardId == .home})))
//        Verify(mockRootNavigator, .setSideMenuRoot(contentViewController: .value(navVc)))
//
//    }
}

// MARK: Privates
private extension TutorialRouterTests {

    func createRouter() -> TutorialRouter {
        let router = TutorialRouter(
            rootNavigator: mockRootNavigator,
            destinationStoryboard: mockStoryboard)

        router.set(viewController: mockViewContoller)

        return router
    }
}



