//
//  LoginOverviewViewControllerTests.swift
//  appointment
//
//  Created by Raluca Mesterca on 03/03/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky
import SnapshotTesting

class LoginOverviewViewControllerTests: XCTestCase {

    // MARK: Mocks
    private let mockRouter = LoginOverviewRouterProtocolMock()

    var sut: LoginOverviewViewController!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()

         // always use simulator for snapshot testing, advisable from iphone 7 higher
         record = SnapshotTestsRecordMode.environmentVariableMappingValue
         sut = createViewController()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
    func testNormal() {
        sut.assertSnapshots()
    }

    // Navigation Methods
    func testLoginButtonTapped() {
        sut.loginButtonTapped(sut!)
        Verify(mockRouter, .route(to: .value(.login)))
    }

    func testRegisterButtonTapped() {
        sut.registerButtonTapped(sut!)
        Verify(mockRouter, .route(to: .value(.register)))
    }

    func testTutorialButtonTapped() {
        sut.tutorialButtonTapped(sut!)
        Verify(mockRouter, .route(to: .value(.tutorial)))
    }
}

// MARK: Privates
private extension  LoginOverviewViewControllerTests {

    func createViewController() ->  LoginOverviewViewController {
        let vc = R.storyboard.login.loginOverviewViewController()!
        vc.view.frame = .init(x: 0, y: 0, width: vc.view.frame.width, height: 1100)
        vc.set(router: mockRouter)
        vc.lifecycle()
        return vc
    }
}
