//
//  HomePagePresenter.swift
//  appointment
//
//  Created by Raluca Mesterca on 18/03/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol HomePagePresenterProtocol {
    func set(viewController: HomePageViewControllerProtocol?)
    func present(isMonthAgenda: Bool)
}

class HomePagePresenter: HomePagePresenterProtocol {

    // MARK: DI
    weak var viewController: HomePageViewControllerProtocol?

    func set(viewController: HomePageViewControllerProtocol?) {
        self.viewController = viewController
    }

    func present(isMonthAgenda: Bool) {
        viewController?.display(isMonthAgenda: isMonthAgenda)
    }
}
