//
//  SetAvailabilityViewControllerRouter.swift
//  appointment
//
//  Created by Jihen on 09/07/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit


//sourcery: AutoMockable
protocol SetAvailabilityRouterProtocol {
    func set(viewController: SetAvailabilityViewControllerProtocol?)
    func route(to scene: SetAvailabilityRouter.Scene)
}

class SetAvailabilityRouter: SetAvailabilityRouterProtocol {
    
    private weak var viewController: SetAvailabilityViewControllerProtocol?

    enum Scene {
        case goBack
    }

    func route(to scene: Scene) {
        switch scene {
        case .goBack:
            viewController?.pop(animated: true)
        }
    }

    func set(viewController: SetAvailabilityViewControllerProtocol?) {
        self.viewController = viewController
    }
}
