//
//  OutGoingRouterTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 3/3/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class OutGoingRouterTests: XCTestCase {

    // MARK: Mocks
    private let mockViewController = OutGoingViewControllerProtocolMock()
    private let mockStoryboard = StoryboardMock()

    func testGotoInvitationDetail() {
        let sut = createRouter()
//        let vc = InvitationDetailViewController()
        let vc = NewInvitationDetailViewController()
        Given(mockStoryboard, .viewController(identifier: .any, willReturn: vc))

        sut.route(to: .invitationDetail(invitation: Appointment.mock()))
        Verify(mockViewController, .show(.value(vc), sender: .any))
        // TODO: fixRouting
        Verify(mockStoryboard, .viewController(identifier: .matching {
            return $0 as? InvitationDetailStoryboardId == .newInvitationDetail
            }))
//        Verify(mockStoryboard, .viewController(identifier: .matching {
//            return $0 as? InvitationDetailStoryboardId == .invitationDetail
//            }))
    }
}

// MARK: Privates
private extension OutGoingRouterTests {

    func createRouter() -> OutGoingRouter {
        let router = OutGoingRouter(invitationDetailStoryboard: mockStoryboard)
        router.set(viewController: mockViewController)
        return router
    }
}
