//
//  HomePresenter.swift
//  appointment
//
//  Created by Raluca Mesterca on 25/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import CoreData

protocol HomePresenterProtocol {
    func set(viewController: HomeViewControllerProtocol?)
}

class HomePresenter: HomePresenterProtocol {

    // MARK: DI
    weak var viewController: HomeViewControllerProtocol?

    func set(viewController: HomeViewControllerProtocol?) {
        self.viewController = viewController
    }
}
