//
//  HomeInteractor.swift
//  appointment
//
//  Created by Raluca Mesterca on 25/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
//import Moya

protocol HomeInteractorProtocol {
}

class HomeInteractor: HomeInteractorProtocol {

    // MARK: - DI
    private let presenter: HomePresenterProtocol

    init(
        presenter: HomePresenterProtocol
    ) {
        self.presenter = presenter
    }
}
