//
//  HomeViewController.swift
//  appointment
//
//  Created by Raluca Mesterca on 25/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import SideMenuSwift

protocol HomeViewControllerProtocol: class, UIViewControllerRouting {
    func set(interactor: HomeInteractorProtocol)
    func set(router: HomeRouterProtocol)
}

class HomeViewController: UIViewController, HomeViewControllerProtocol {

    // MARK: DI
    var interactor: HomeInteractorProtocol?
    var router: HomeRouterProtocol?

    func set(interactor: HomeInteractorProtocol) {
        self.interactor = interactor
    }

    func set(router: HomeRouterProtocol) {
        self.router = router
    }

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()

        setUpNavigationBar()
    }

    // MARK: Actions
    @IBAction func menuButtonTapped(_ sender: UIButton) {
        sideMenuController?.revealMenu()
    }
}

// MARK: Configure Methods
private extension HomeViewController {

    // swiftlint:disable discouraged_object_literal
    func setUpNavigationBar() {
        let yearButton = navigationController?.drawYearButton()
        navigationItem.title = ""
        let menuItem = UIBarButtonItem(image: #imageLiteral(resourceName: "Menu_Button"), style: .plain, target: self, action: #selector(menuButtonTapped))
        let timeLineMenu = UIBarButtonItem(image: #imageLiteral(resourceName: "Landing_Dots"), style: .plain, target: self, action: #selector(menuButtonTapped))
        let timeLineCalendar = UIBarButtonItem(image: #imageLiteral(resourceName: "Landing_Planning"), style: .plain, target: self, action: #selector(menuButtonTapped))
        navigationItem.rightBarButtonItems = [timeLineMenu, timeLineCalendar]
        navigationItem.leftBarButtonItems = [menuItem, yearButton!]
    }
}

// TO DO: floating button - open chat + make appointment
// TO DO: switch though calendar types + floating menu
