//
//  LoginPresenter.swift
//  appointment
//
//  Created by Raluca Mesterca on 13/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit
import p2_OAuth2

//sourcery: AutoMockable
protocol LoginPresenterProtocol {
    func set(viewController: LoginViewControllerProtocol)
    
    func presentInvalidData(_ error: DataValidationError)
    
    func presentLoginSuccess()
    func presentLoginError()
}

class LoginPresenter: LoginPresenterProtocol {
    weak var viewController: LoginViewControllerProtocol?

    // MARK: Do something

    func set(viewController: LoginViewControllerProtocol) {
        self.viewController = viewController
    }
    
    func presentLoginSuccess() {
        viewController?.handleLoginSuccess()
    }
    
    func presentLoginError() {
        viewController?.handleLoginFailure(error: AuthError.wrongCredentials.localizedDescription)
    }
    
    func presentInvalidData(_ error: DataValidationError) {
        switch error {
        case .emptyEmail, .invalidEmail:
            viewController?.displayInvalidEmail(error: error.localizedDescription)
        case .emptyPassword, .invalidPassword:
            viewController?.displayInvalidPassword(error: error.localizedDescription)
        case .emptyFields:
            viewController?.displayGeneric(error: error.localizedDescription)
        default:
            break
        }
    }
}
