//
//  RegisterRouterTests.swift
//  appointment
//
//  Created by Rachel Polachova on 27/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class RegisterRouterTests: XCTestCase {

    // MARK: Subject under test
    private let mockViewController = RegisterViewControllerProtocolMock()
    private let mockRootNavigator = RootNavigatorProtocolMock()
    private let mockStoryboard = StoryboardMock()

    private var sut: RegisterRouter!
    
    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        sut = createRegisterRouter()
    }
    
    override func tearDown() {
        sut = nil
        super.tearDown()
    }
    
    // MARK: Tests
    func testRouteLogin() {
        let vc = LoginViewController()
        Given(mockStoryboard, .viewController(identifier: .any, willReturn: vc))

        sut.route(to: .login)

        Verify(mockStoryboard, .viewController(identifier: .matching({  return $0 as? LoginStoryboardId == .login
        })))
        Verify(mockViewController, .show(.value(vc), sender: .any))
    }

//    func testRouteToHome() {
//        let vc = HomeViewController()
//        let navVC = ApplicationNavigationController(rootViewController: vc)
//        Given(mockStoryboard, .viewController(identifier: .any, willReturn: vc))
//
//        sut.route(to: .home)
//        Verify(mockStoryboard, .viewController(identifier: .matching({ return $0 as? HomeStoryboardId == .home
//        })))
//        
//        Verify(mockRootNavigator, .setSideMenuRoot(contentViewController: .value(navVC)))
//    }
    
    func testRouteLoginOverview() {
        sut.route(to: .loginOverView)
        Verify(mockViewController, .popToRoot(animated: .any))
    }
}

// MARK: Privates
private extension RegisterRouterTests {

    func createRegisterRouter() -> RegisterRouter {
        let router = RegisterRouter(
            rootNavigator: mockRootNavigator,
            registerStoryboard: mockStoryboard,
            loginStoryboard: mockStoryboard,
            homeStoryboard: mockStoryboard)
        router.set(viewController: mockViewController)
        return router
    }
}
