////
//  ForgotPasswordRouter.swift
//  appointment
//
//  Created by Youssef Jdidi on 2/20/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol ForgotPasswordRouterProtocol {
  func set(viewController: ForgotPasswordViewControllerProtocol?)
  func route(to scene: ForgotPasswordRouter.Scene)
}

class ForgotPasswordRouter: NSObject, ForgotPasswordRouterProtocol {

    // MARK: DI
    weak var viewController: ForgotPasswordViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let destinationStoryboard: Storyboard

    func set(viewController: ForgotPasswordViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        destinationStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.destinationStoryboard = destinationStoryboard
    }
}

// MARK: Routing logic
extension ForgotPasswordRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: ForgotPasswordRouter.Scene) {
        switch scene {
        case .destination1:
            break
        }
    }
}
