//
//  ForgotPasswordPresenter.swift
//  appointment
//
//  Created by Youssef Jdidi on 2/20/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol ForgotPasswordPresenterProtocol {
    func set(viewController: ForgotPasswordViewControllerProtocol?)
    
    func presentValidationError(_ error: DataValidationError)
    func presentValidationSuccess()
    
    func presentEmailSentSuccess()
    func presentEmailSentError(_ error: ForgotPasswordError)
}

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol {

    // MARK: DI
    weak var viewController: ForgotPasswordViewControllerProtocol?

    func set(viewController: ForgotPasswordViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  ForgotPasswordPresenter {

    func presentValidationError(_ error: DataValidationError) {
        viewController?.displayValidationError(error.localizedDescription)
    }
    
    func presentValidationSuccess() {
        viewController?.displayValidationSuccess()
    }
    
    func presentEmailSentError(_ error: ForgotPasswordError) {
        viewController?.displayEmailSentError(error)
    }
    
    func presentEmailSentSuccess() {
        viewController?.displayEmailSentSuccess()
    }
}
