//
//  TutorialPresenter.swift
//  appointment
//
//  Created by Rachel Polachova on 21/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol TutorialPresenterProtocol: class {
    func set(viewController: TutorialViewControllerProtocol?)

    func handle(error: Error)
    func displayTutorialSlides(_ slides: [Tutorial])
    func displayActivityIndicator(_ display: Bool)
}

class TutorialPresenter: TutorialPresenterProtocol {

    // MARK: DI
    weak var viewController: TutorialViewControllerProtocol?

    func set(viewController: TutorialViewControllerProtocol?) {
        self.viewController = viewController
    }
}

// MARK: Methods
extension  TutorialPresenter {

    func handle(error: Error) {
        viewController?.display(error: error)
    }
    
    func displayTutorialSlides(_ slides: [Tutorial]) {
        viewController?.displayTutorialSlides(with: slides)
    }
    
    func displayActivityIndicator(_ display: Bool) {
        viewController?.displayActivityIndicator(display)
    }
}
