//
//  TutorialInteractor.swift
//  appointment
//
//  Created by Rachel Polachova on 21/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol TutorialInteractorProtocol {
    func fetchTutorialPages()
}

class TutorialInteractor: TutorialInteractorProtocol {
    
    // MARK: DI
    var presenter: TutorialPresenterProtocol
    private let service: TutorialServiceProtocol

    init(
        presenter: TutorialPresenterProtocol,
        service: TutorialServiceProtocol
    ) {
        self.presenter = presenter
        self.service = service
    }
    
    func fetchTutorialPages() {
        presenter.displayActivityIndicator(true)
        service.fetchTutorialSlides { [weak self] result in
            self?.presenter.displayActivityIndicator(false)
            switch result {
            case .success(let response):
                self?.handleTutorialResponse(result: response)
            case .failure(let error):
                self?.presenter.handle(error: error)
            }
        }
    }
}

// MARK: Private methods
private extension TutorialInteractor {

    func handleTutorialResponse(result: TutorialResponse) {
//        let result = response
        var tutorials = [Tutorial]()
        tutorials.append(Tutorial(title: result.titlePage1, description: result.descriptionPage1, imageUrl: result.imageUrl1))
        tutorials.append(Tutorial(title: result.titlePage2, description: result.descriptionPage2, imageUrl: result.imageUrl2))
        tutorials.append(Tutorial(title: result.titlePage3, description: result.descriptionPage3, imageUrl: result.imageUrl3))
        tutorials.append(Tutorial(title: result.titlePage4, description: result.descriptionPage4, imageUrl: result.imageUrl4))
        tutorials.append(Tutorial(title: result.titlePage5, description: result.descriptionPage5, imageUrl: result.imageUrl5))
        presenter.displayTutorialSlides(tutorials)
    }
}
