//
//  SettingsPresenterTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 6/11/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class SettingsPresenterTests: XCTestCase {

    // MARK: Mocks
    private let mockViewController = SettingsViewControllerProtocolMock()
    private var sut: SettingsPresenter!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()

        sut = createPresenter()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
}

// MARK: - Privates
private extension SettingsPresenterTests {

    func createPresenter() -> SettingsPresenter {
        let presenter =  SettingsPresenter()
        presenter.set(viewController: mockViewController)
        return presenter
    }
}


