//
//  SettingsInteractorTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 6/11/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class SettingsInteractorTests: XCTestCase {

    // MARK: Mocks
    private let mockPresenter = SettingsPresenterProtocolMock()
    private let mockService = SettingsServiceProtocolMock()
    private let mockAuthManager = AuthManagerProtocolMock()
    private let mockErrorHandler = ErrorHandlerProtocolMock()
    private let mockUserData = CurrentUserDataServiceProtocolMock()
    private let mockSettingsDataService = SettingsDataServiceProtocolMock()

    private var sut: SettingsInteractor!

    // MARK: Test lifecycle
    override func setUp()   {
        super.setUp()

        sut = createInteractor()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
}

// MARK: Privates
private extension  SettingsInteractorTests {

    func createInteractor() ->  SettingsInteractor {
        // initialize the interactor
        return .init(presenter: mockPresenter, settingsService: mockService, settingsDataService: mockSettingsDataService, authManager: mockAuthManager, userDataService: mockUserData, errorHandler: mockErrorHandler)
    }
}
