//
//  SettingsRouterTests.swift
//  appointment
//
//  Created by Youssef Jdidi on 6/11/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import appointment
import XCTest
import SwiftyMocky

class SettingsRouterTests: XCTestCase {

    // MARK: Mocks
    private let mockViewController = SettingsViewControllerProtocolMock()
    private let mockRootNavigator = RootNavigatorProtocolMock()
    private let mockStoryboard = StoryboardMock()
    private let mockLoginStoryboard = StoryboardMock()
    private let mockpopupStoryboard = StoryboardMock()

    var sut: SettingsRouter!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        sut = createRouter()
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: Tests
}

// MARK: Privates
private extension SettingsRouterTests {

    func createRouter() -> SettingsRouter {
        return .init(rootNavigator: mockRootNavigator, loginStoryboard: mockLoginStoryboard, popupStoryboard: mockpopupStoryboard)
    }
}



