//
//  LoginOverviewViewController.swift
//  appointment
//
//  Created by Raluca Mesterca on 13/02/2020.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

//sourcery: AutoMockable
protocol LoginOverviewViewControllerProtocol: class, UIViewControllerRouting {
    func set(router: LoginOverviewRouterProtocol)
}

class LoginOverviewViewController: UIViewController, LoginOverviewViewControllerProtocol {

    // MARK: DI
    var router: LoginOverviewRouterProtocol?

    func set(router: LoginOverviewRouterProtocol) {
        self.router = router
    }

    // MARK: Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)

        navigationController?.setNavigationBarHidden(false, animated: false)
    }

    // MARK: Actions
    @IBAction func loginButtonTapped(_ sender: Any) {
        router?.route(to: .login)
    }
    @IBAction func registerButtonTapped(_ sender: Any) {
        router?.route(to: .register)
    }
    @IBAction func tutorialButtonTapped(_ sender: Any) {
        router?.route(to: .tutorial)
    }
}
