////
//  AddToAgendaRouter.swift
//  appointment
//
//  Created by Youssef Jdidi on 7/14/20.
//  Copyright (c) 2020 DTT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  This template is meant to work with Swinject.

import UIKit

protocol AddToAgendaRouterProtocol {
  func set(viewController: AddToAgendaViewControllerProtocol?)
  func route(to scene: AddToAgendaRouter.Scene)
}

class AddToAgendaRouter: NSObject, AddToAgendaRouterProtocol {

    // MARK: DI
    weak var viewController: AddToAgendaViewControllerProtocol?
    private let rootNavigator: RootNavigatorProtocol
    private let invitationDetailStoryboard: Storyboard

    func set(viewController: AddToAgendaViewControllerProtocol?) {
        self.viewController = viewController
    }

    init(
        rootNavigator: RootNavigatorProtocol,
        invitationDetailStoryboard: Storyboard
    ) {
        self.rootNavigator = rootNavigator
        self.invitationDetailStoryboard = invitationDetailStoryboard
    }
}

// MARK: Routing logic
extension AddToAgendaRouter {

    enum Scene {
        case destination1
    }

    func route(to scene: AddToAgendaRouter.Scene) {
        switch scene {
        case .destination1: break
        }
    }
}
